<?php
/**
 * Data for terms migration
 */

/**
 * Get data for transforming WP terms to Hugo terms
 *
 * @param int|string $term_id WordPress term ID, integer or numeric string
 * @return array|null Term data with Hugo taxonomy and term strings, or null if not found
 */
function hh_hugo_get_term_data( $term_id ) {
	$terms_data = array(
		310 => array( 'taxonomy' => 'groups', 'term' => 'Amman' ),
		386 => array( 'taxonomy' => 'groups', 'term' => 'Amman' ),
		108 => array( 'taxonomy' => 'tags', 'term' => 'Android' ),
		78 => array( 'taxonomy' => 'categories', 'term' => 'Announcements' ),
		74 => array( 'taxonomy' => 'tags', 'term' => 'API' ),
		122 => array( 'taxonomy' => 'tags', 'term' => 'APM' ),
		106 => array( 'taxonomy' => 'tags', 'term' => 'Apps' ),
		315 => array( 'taxonomy' => 'tags', 'term' => 'Arab World' ),
		229 => array( 'taxonomy' => 'tags', 'term' => 'Argentina' ),
		272 => array( 'taxonomy' => 'groups', 'term' => 'Armenia' ),
		363 => array( 'taxonomy' => 'groups', 'term' => 'Asunción' ),
		131 => array( 'taxonomy' => 'groups', 'term' => 'Atlanta' ),
		100 => array( 'taxonomy' => 'groups', 'term' => 'Austin' ),
		377 => array( 'taxonomy' => 'groups', 'term' => 'Austin' ),
		114 => array( 'taxonomy' => 'groups', 'term' => 'Bay Area' ),
		116 => array( 'taxonomy' => 'groups', 'term' => 'Bay Area' ),
		129 => array( 'taxonomy' => 'tags', 'term' => 'Belgium' ),
		295 => array( 'taxonomy' => 'groups', 'term' => 'Berlin' ),
		294 => array( 'taxonomy' => 'groups', 'term' => 'Berlin' ),
		288 => array( 'taxonomy' => 'groups', 'term' => 'Bogotá' ),
		382 => array( 'taxonomy' => 'groups', 'term' => 'Bogotá' ),
		64 => array( 'taxonomy' => 'groups', 'term' => 'Boston' ),
		71 => array( 'taxonomy' => 'groups', 'term' => 'Boston' ),
		72 => array( 'taxonomy' => 'groups', 'term' => 'Boston' ),
		290 => array( 'taxonomy' => 'tags', 'term' => 'Brasil' ),
		291 => array( 'taxonomy' => 'tags', 'term' => 'Brasil' ),
		261 => array( 'taxonomy' => 'groups', 'term' => 'Brighton' ),
		289 => array( 'taxonomy' => 'groups', 'term' => 'Brighton' ),
		134 => array( 'taxonomy' => 'groups', 'term' => 'Brussels' ),
		379 => array( 'taxonomy' => 'groups', 'term' => 'Brussels' ),
		227 => array( 'taxonomy' => 'groups', 'term' => 'Buenos Aires' ),
		231 => array( 'taxonomy' => 'groups', 'term' => 'Buenos Aires' ),
		19 => array( 'taxonomy' => 'tags', 'term' => 'business model' ),
		293 => array( 'taxonomy' => 'groups', 'term' => 'Canterbury' ),
		384 => array( 'taxonomy' => 'groups', 'term' => 'Canterbury' ),
		153 => array( 'taxonomy' => 'tags', 'term' => 'maps' ),
		278 => array( 'taxonomy' => 'tags', 'term' => 'census' ),
		65 => array( 'taxonomy' => 'groups', 'term' => 'Chicago' ),
		216 => array( 'taxonomy' => 'categories', 'term' => 'Classes' ),
		331 => array( 'taxonomy' => 'tags', 'term' => 'Code With Me' ),
		36 => array( 'taxonomy' => 'tags', 'term' => 'collaboration' ),
		33 => array( 'taxonomy' => 'tags', 'term' => 'collaboration' ),
		252 => array( 'taxonomy' => 'groups', 'term' => 'Colorado' ),
		253 => array( 'taxonomy' => 'tags', 'term' => 'comments' ),
		373 => array( 'taxonomy' => 'tags', 'term' => 'Connect' ),
		17 => array( 'taxonomy' => 'tags', 'term' => 'content aggregator' ),
		49 => array( 'taxonomy' => 'tags', 'term' => 'content management system' ),
		282 => array( 'taxonomy' => 'tags', 'term' => 'contest' ),
		333 => array( 'taxonomy' => 'groups', 'term' => 'Copenhagen' ),
		300 => array( 'taxonomy' => 'tags', 'term' => 'crowdsourcing' ),
		15 => array( 'taxonomy' => 'tags', 'term' => 'curation' ),
		48 => array( 'taxonomy' => 'tags', 'term' => 'data' ),
		47 => array( 'taxonomy' => 'tags', 'term' => 'data visualization' ),
		179 => array( 'taxonomy' => 'tags', 'term' => 'data visualization' ),
		73 => array( 'taxonomy' => 'tags', 'term' => 'daylife' ),
		69 => array( 'taxonomy' => 'categories', 'term' => 'Demos' ),
		147 => array( 'taxonomy' => 'categories', 'term' => 'Demos' ),
		332 => array( 'taxonomy' => 'tags', 'term' => 'demo day' ),
		70 => array( 'taxonomy' => 'categories', 'term' => 'Demos' ),
		327 => array( 'taxonomy' => 'tags', 'term' => 'Denmark' ),
		6 => array( 'taxonomy' => 'tags', 'term' => 'design' ),
		51 => array( 'taxonomy' => 'tags', 'term' => 'development' ),
		230 => array( 'taxonomy' => 'tags', 'term' => 'digital' ),
		60 => array( 'taxonomy' => 'tags', 'term' => 'digital paper' ),
		240 => array( 'taxonomy' => 'tags', 'term' => 'Drumbeat' ),
		314 => array( 'taxonomy' => 'tags', 'term' => 'Drupal' ),
		339 => array( 'taxonomy' => 'groups', 'term' => 'Dublin' ),
		189 => array( 'taxonomy' => 'tags', 'term' => 'editflow' ),
		258 => array( 'taxonomy' => 'tags', 'term' => 'education' ),
		235 => array( 'taxonomy' => 'tags', 'term' => 'entrepreneurship' ),
		299 => array( 'taxonomy' => 'tags', 'term' => 'environment' ),
		24 => array( 'taxonomy' => 'tags', 'term' => 'event ideas' ),
		90 => array( 'taxonomy' => 'tags', 'term' => 'events' ),
		376 => array( 'taxonomy' => 'tags', 'term' => 'Facebook' ),
		243 => array( 'taxonomy' => 'tags', 'term' => 'fellowship' ),
		171 => array( 'taxonomy' => 'tags', 'term' => 'Filibusted' ),
		139 => array( 'taxonomy' => 'tags', 'term' => 'Forms' ),
		181 => array( 'taxonomy' => 'tags', 'term' => 'foursquare' ),
		380 => array( 'taxonomy' => 'tags', 'term' => 'Gaming' ),
		176 => array( 'taxonomy' => 'tags', 'term' => 'Gaming' ),
		92 => array( 'taxonomy' => 'tags', 'term' => 'gawker' ),
		32 => array( 'taxonomy' => 'tags', 'term' => 'google' ),
		175 => array( 'taxonomy' => 'tags', 'term' => 'Google Fusion Tables' ),
		275 => array( 'taxonomy' => 'tags', 'term' => 'Google Fusion Tables' ),
		34 => array( 'taxonomy' => 'tags', 'term' => 'google wave' ),
		127 => array( 'taxonomy' => 'tags', 'term' => 'Great Urban Hack' ),
		23 => array( 'taxonomy' => 'tags', 'term' => 'hack day' ),
		103 => array( 'taxonomy' => 'tags', 'term' => 'Hackathons' ),
		67 => array( 'taxonomy' => 'tags', 'term' => 'Hackathons' ),
		21 => array( 'taxonomy' => 'tags', 'term' => 'hackers' ),
		75 => array( 'taxonomy' => 'tags', 'term' => 'hacking' ),
		20 => array( 'taxonomy' => 'tags', 'term' => 'hacks' ),
		340 => array( 'taxonomy' => 'groups', 'term' => 'Zürich' ),
		141 => array( 'taxonomy' => 'groups', 'term' => 'Atlanta' ),
		150 => array( 'taxonomy' => 'tags', 'term' => 'Happy Holidays!' ),
		217 => array( 'taxonomy' => 'groups', 'term' => 'Heartland' ),
		140 => array( 'taxonomy' => 'groups', 'term' => 'Atlanta' ),
		328 => array( 'taxonomy' => 'groups', 'term' => 'Rosario' ),
		148 => array( 'taxonomy' => 'tags', 'term' => 'Happy Holidays!' ),
		360 => array( 'taxonomy' => 'groups', 'term' => 'Hong Kong' ),
		390 => array( 'taxonomy' => 'groups', 'term' => 'Hong Kong' ),
		89 => array( 'taxonomy' => 'tags', 'term' => 'HTML5' ),
		324 => array( 'taxonomy' => 'tags', 'term' => 'iconathon' ),
		321 => array( 'taxonomy' => 'tags', 'term' => 'icons' ),
		319 => array( 'taxonomy' => 'groups', 'term' => 'India' ),
		130 => array( 'taxonomy' => 'tags', 'term' => 'information graphics' ),
		5 => array( 'taxonomy' => 'tags', 'term' => 'innovation' ),
		28 => array( 'taxonomy' => 'tags', 'term' => 'internet news' ),
		323 => array( 'taxonomy' => 'tags', 'term' => 'investigative journalism' ),
		45 => array( 'taxonomy' => 'tags', 'term' => 'iPad' ),
		285 => array( 'taxonomy' => 'categories', 'term' => 'Jobs' ),
		311 => array( 'taxonomy' => 'groups', 'term' => 'Amman' ),
		226 => array( 'taxonomy' => 'tags', 'term' => 'journalism' ),
		77 => array( 'taxonomy' => 'tags', 'term' => 'journalism education' ),
		136 => array( 'taxonomy' => 'tags', 'term' => 'Kickoff' ),
		234 => array( 'taxonomy' => 'tags', 'term' => 'Knight fellowships' ),
		242 => array( 'taxonomy' => 'tags', 'term' => 'Knight Foundation' ),
		115 => array( 'taxonomy' => 'tags', 'term' => 'knight news challenge' ),
		281 => array( 'taxonomy' => 'tags', 'term' => 'knight-mozilla' ),
		239 => array( 'taxonomy' => 'tags', 'term' => 'knight news challenge' ),
		232 => array( 'taxonomy' => 'tags', 'term' => 'Latin America' ),
		354 => array( 'taxonomy' => 'tags', 'term' => 'learn' ),
		218 => array( 'taxonomy' => 'tags', 'term' => 'Lightning Talks' ),
		102 => array( 'taxonomy' => 'tags', 'term' => 'Networking' ),
		142 => array( 'taxonomy' => 'tags', 'term' => 'logos' ),
		250 => array( 'taxonomy' => 'groups', 'term' => 'London' ),
		85 => array( 'taxonomy' => 'groups', 'term' => 'London' ),
		76 => array( 'taxonomy' => 'groups', 'term' => 'Los Angeles' ),
		375 => array( 'taxonomy' => 'groups', 'term' => 'Los Angeles' ),
		266 => array( 'taxonomy' => 'groups', 'term' => 'Madrid' ),
		381 => array( 'taxonomy' => 'groups', 'term' => 'Madrid' ),
		274 => array( 'taxonomy' => 'tags', 'term' => 'Maps' ),
		152 => array( 'taxonomy' => 'tags', 'term' => 'Maps' ),
		361 => array( 'taxonomy' => 'tags', 'term' => 'media' ),
		12 => array( 'taxonomy' => 'tags', 'term' => 'media revolution' ),
		38 => array( 'taxonomy' => 'tags', 'term' => 'medill school of journalism' ),
		355 => array( 'taxonomy' => 'tags', 'term' => 'Meetups' ),
		3 => array( 'taxonomy' => 'categories', 'term' => 'Meetups' ),
		62 => array( 'taxonomy' => 'categories', 'term' => 'Meetups' ),
		374 => array( 'taxonomy' => 'categories', 'term' => 'Meetups' ),
		320 => array( 'taxonomy' => 'groups', 'term' => 'Miami' ),
		313 => array( 'taxonomy' => 'tags', 'term' => 'Middle East' ),
		133 => array( 'taxonomy' => 'tags', 'term' => 'MIT' ),
		113 => array( 'taxonomy' => 'groups', 'term' => 'Mobile' ),
		105 => array( 'taxonomy' => 'groups', 'term' => 'Mobile' ),
		107 => array( 'taxonomy' => 'tags', 'term' => 'mobile apps' ),
		241 => array( 'taxonomy' => 'tags', 'term' => 'Mojo' ),
		83 => array( 'taxonomy' => 'tags', 'term' => 'Mozilla' ),
		316 => array( 'taxonomy' => 'groups', 'term' => 'New Delhi' ),
		387 => array( 'taxonomy' => 'groups', 'term' => 'New Delhi' ),
		56 => array( 'taxonomy' => 'groups', 'term' => 'New York' ),
		63 => array( 'taxonomy' => 'groups', 'term' => 'New York' ),
		334 => array( 'taxonomy' => 'tags', 'term' => 'New York Public Library' ),
		37 => array( 'taxonomy' => 'tags', 'term' => 'New York Times' ),
		238 => array( 'taxonomy' => 'categories', 'term' => 'News' ),
		50 => array( 'taxonomy' => 'tags', 'term' => 'news applications' ),
		27 => array( 'taxonomy' => 'tags', 'term' => 'news tools' ),
		186 => array( 'taxonomy' => 'tags', 'term' => 'newscred' ),
		371 => array( 'taxonomy' => 'categories', 'term' => 'Newsletter' ),
		372 => array( 'taxonomy' => 'categories', 'term' => 'Newsletter' ),
		41 => array( 'taxonomy' => 'tags', 'term' => 'newsroom' ),
		191 => array( 'taxonomy' => 'groups', 'term' => 'New York' ),
		193 => array( 'taxonomy' => 'groups', 'term' => 'New York' ),
		156 => array( 'taxonomy' => 'tags', 'term' => 'ngram' ),
		362 => array( 'taxonomy' => 'tags', 'term' => 'nicar' ),
		120 => array( 'taxonomy' => 'tags', 'term' => 'npr' ),
		192 => array( 'taxonomy' => 'tags', 'term' => 'NWC' ),
		112 => array( 'taxonomy' => 'tags', 'term' => 'nyc' ),
		335 => array( 'taxonomy' => 'tags', 'term' => 'NYPL Labs' ),
		110 => array( 'taxonomy' => 'tags', 'term' => 'Online News Association' ),
		109 => array( 'taxonomy' => 'tags', 'term' => 'open source' ),
		132 => array( 'taxonomy' => 'tags', 'term' => 'OpenBlock' ),
		182 => array( 'taxonomy' => 'tags', 'term' => 'opencongress' ),
		178 => array( 'taxonomy' => 'tags', 'term' => 'opendata' ),
		358 => array( 'taxonomy' => 'tags', 'term' => 'opendatacity' ),
		177 => array( 'taxonomy' => 'tags', 'term' => 'opengov' ),
		138 => array( 'taxonomy' => 'categories', 'term' => 'Opportunities' ),
		246 => array( 'taxonomy' => 'groups', 'term' => 'Ottawa' ),
		247 => array( 'taxonomy' => 'groups', 'term' => 'Ottawa' ),
		84 => array( 'taxonomy' => 'tags', 'term' => 'P2PU' ),
		307 => array( 'taxonomy' => 'groups', 'term' => 'Paris' ),
		385 => array( 'taxonomy' => 'groups', 'term' => 'Paris' ),
		91 => array( 'taxonomy' => 'tags', 'term' => 'party' ),
		268 => array( 'taxonomy' => 'tags', 'term' => 'Periodismo' ),
		13 => array( 'taxonomy' => 'tags', 'term' => 'personalized news' ),
		265 => array( 'taxonomy' => 'groups', 'term' => 'Philadelphia' ),
		248 => array( 'taxonomy' => 'tags', 'term' => 'politics' ),
		94 => array( 'taxonomy' => 'tags', 'term' => 'PolitiFact' ),
		80 => array( 'taxonomy' => 'tags', 'term' => 'Poynter' ),
		86 => array( 'taxonomy' => 'tags', 'term' => 'Programming for Journalists' ),
		183 => array( 'taxonomy' => 'tags', 'term' => 'ProPublica' ),
		121 => array( 'taxonomy' => 'tags', 'term' => 'PRX' ),
		337 => array( 'taxonomy' => 'tags', 'term' => 'public participation' ),
		190 => array( 'taxonomy' => 'tags', 'term' => 'publishing' ),
		118 => array( 'taxonomy' => 'tags', 'term' => 'pubmedia' ),
		219 => array( 'taxonomy' => 'tags', 'term' => 'python' ),
		26 => array( 'taxonomy' => 'tags', 'term' => 'question and answer' ),
		52 => array( 'taxonomy' => 'tags', 'term' => 'question and answer' ),
		317 => array( 'taxonomy' => 'groups', 'term' => 'Rabat' ),
		388 => array( 'taxonomy' => 'groups', 'term' => 'Rabat' ),
		119 => array( 'taxonomy' => 'tags', 'term' => 'radio' ),
		359 => array( 'taxonomy' => 'tags', 'term' => 're:publica' ),
		35 => array( 'taxonomy' => 'tags', 'term' => 'real-time' ),
		39 => array( 'taxonomy' => 'tags', 'term' => 'robots' ),
		330 => array( 'taxonomy' => 'groups', 'term' => 'Rosario' ),
		308 => array( 'taxonomy' => 'tags', 'term' => 'rue89' ),
		292 => array( 'taxonomy' => 'groups', 'term' => 'São Paulo' ),
		383 => array( 'taxonomy' => 'groups', 'term' => 'São Paulo' ),
		79 => array( 'taxonomy' => 'tags', 'term' => 'scholarship' ),
		128 => array( 'taxonomy' => 'groups', 'term' => 'Seattle' ),
		378 => array( 'taxonomy' => 'groups', 'term' => 'Seattle' ),
		236 => array( 'taxonomy' => 'groups', 'term' => 'Silicon Valley' ),
		185 => array( 'taxonomy' => 'tags', 'term' => 'slate' ),
		312 => array( 'taxonomy' => 'tags', 'term' => 'SMS' ),
		93 => array( 'taxonomy' => 'tags', 'term' => 'social' ),
		44 => array( 'taxonomy' => 'tags', 'term' => 'social media' ),
		43 => array( 'taxonomy' => 'tags', 'term' => 'social media' ),
		30 => array( 'taxonomy' => 'tags', 'term' => 'social news' ),
		225 => array( 'taxonomy' => 'tags', 'term' => 'software' ),
		42 => array( 'taxonomy' => 'tags', 'term' => 'source control' ),
		286 => array( 'taxonomy' => 'tags', 'term' => 'Southern Methodist University' ),
		126 => array( 'taxonomy' => 'groups', 'term' => 'St. Louis' ),
		53 => array( 'taxonomy' => 'tags', 'term' => 'Stack Overflow' ),
		154 => array( 'taxonomy' => 'tags', 'term' => 'Stamen' ),
		237 => array( 'taxonomy' => 'tags', 'term' => 'Stanford University' ),
		296 => array( 'taxonomy' => 'tags', 'term' => 'startup' ),
		98 => array( 'taxonomy' => 'tags', 'term' => 'Stats Monkey' ),
		353 => array( 'taxonomy' => 'tags', 'term' => 'stickers' ),
		55 => array( 'taxonomy' => 'tags', 'term' => 'storytelling' ),
		144 => array( 'taxonomy' => 'tags', 'term' => 'style guide' ),
		194 => array( 'taxonomy' => 'tags', 'term' => 'SXSW' ),
		325 => array( 'taxonomy' => 'tags', 'term' => 'Tableau' ),
		187 => array( 'taxonomy' => 'tags', 'term' => 'talkingpointsmemo' ),
		68 => array( 'taxonomy' => 'categories', 'term' => 'Talks' ),
		254 => array( 'taxonomy' => 'categories', 'term' => 'Talks' ),
		270 => array( 'taxonomy' => 'tags', 'term' => 'Tecnologia' ),
		22 => array( 'taxonomy' => 'tags', 'term' => 'tension' ),
		287 => array( 'taxonomy' => 'tags', 'term' => 'Texas State University' ),
		304 => array( 'taxonomy' => 'tags', 'term' => 'texas tribune' ),
		184 => array( 'taxonomy' => 'tags', 'term' => 'texttoggle' ),
		263 => array( 'taxonomy' => 'tags', 'term' => 'The Guardian' ),
		104 => array( 'taxonomy' => 'tags', 'term' => 'The Media Consortium' ),
		322 => array( 'taxonomy' => 'tags', 'term' => 'The Noun Project' ),
		124 => array( 'taxonomy' => 'groups', 'term' => 'Toronto' ),
		146 => array( 'taxonomy' => 'groups', 'term' => 'Toronto' ),
		125 => array( 'taxonomy' => 'groups', 'term' => 'Toronto' ),
		188 => array( 'taxonomy' => 'tags', 'term' => 'tpm' ),
		336 => array( 'taxonomy' => 'tags', 'term' => 'transcription' ),
		233 => array( 'taxonomy' => 'groups', 'term' => 'Twin Cities' ),
		260 => array( 'taxonomy' => 'tags', 'term' => 'UI' ),
		297 => array( 'taxonomy' => 'groups', 'term' => 'Usahidi' ),
		18 => array( 'taxonomy' => 'tags', 'term' => 'UX' ),
		7 => array( 'taxonomy' => 'tags', 'term' => 'user-centered' ),
		101 => array( 'taxonomy' => 'groups', 'term' => 'Usahidi' ),
		259 => array( 'taxonomy' => 'tags', 'term' => 'UX' ),
		244 => array( 'taxonomy' => 'tags', 'term' => 'video' ),
		180 => array( 'taxonomy' => 'tags', 'term' => 'vizthink' ),
		277 => array( 'taxonomy' => 'tags', 'term' => 'Wall Street Journal' ),
		66 => array( 'taxonomy' => 'groups', 'term' => 'Washington DC' ),
		111 => array( 'taxonomy' => 'groups', 'term' => 'Washington DC' ),
		172 => array( 'taxonomy' => 'tags', 'term' => 'WBUR' ),
		40 => array( 'taxonomy' => 'tags', 'term' => 'web applications' ),
		4 => array( 'taxonomy' => 'tags', 'term' => 'welcome' ),
		151 => array( 'taxonomy' => 'tags', 'term' => 'Wikileaks' ),
		276 => array( 'taxonomy' => 'tags', 'term' => 'WNYC' ),
		137 => array( 'taxonomy' => 'tags', 'term' => 'WordPress' ),
		271 => array( 'taxonomy' => 'groups', 'term' => 'Yerevan' ),
		318 => array( 'taxonomy' => 'groups', 'term' => 'Yerevan' ),
		338 => array( 'taxonomy' => 'groups', 'term' => 'Zürich' ),
		389 => array( 'taxonomy' => 'groups', 'term' => 'Zürich' ),
	);

	$term_id = intval( $term_id );
	return isset( $terms_data[ $term_id ] ) ? $terms_data[ $term_id ] : null;
}
